---
  name: End-to-end tests
  on:
    schedule:
      - cron: "*/5 * * * *"
  jobs:
    cypress-run:
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            browser: chrome
            record: true
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.RECORDING_KEY }}
        - name: Print Cypress Cloud URL
          run: |
            echo Cypress finished with: ${{ steps.cypress.outcome }}
            echo See results at ${{ steps.cypress.outputs.resultsUrl }}