name: End-to-end tests
on:
  schedule:
    # runs tests every 30 mins
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npx run build
          start: npx cypress run --record --key 313783b8-994b-4a56-98a5-61a7c11f7bcc
          browser: chrome